// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CoreProto.proto

#import "GPBProtocolBuffers.h"

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30000
#error This file was generated by a different version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - CoreProtoRoot

@interface CoreProtoRoot : GPBRootObject

// The base class provides:
//   + (GPBExtensionRegistry *)extensionRegistry;
// which is an GPBExtensionRegistry that includes all the extensions defined by
// this file and all files that it depends on.

@end

#pragma mark - MobileMessage

typedef GPB_ENUM(MobileMessage_FieldNumber) {
  MobileMessage_FieldNumber_Version = 1,
  MobileMessage_FieldNumber_Type = 2,
  MobileMessage_FieldNumber_MobileId = 3,
  MobileMessage_FieldNumber_MobileToken = 4,
  MobileMessage_FieldNumber_PayloadArray = 100,
};

@interface MobileMessage : GPBMessage

@property(nonatomic, readwrite) int32_t version;

@property(nonatomic, readwrite) int32_t type;

@property(nonatomic, readwrite, copy, null_resettable) NSString *mobileId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *mobileToken;

// |payloadArray| contains |GPBAny|
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray *payloadArray;
@property(nonatomic, readonly) NSUInteger payloadArray_Count;

@end

#pragma mark - ServerMessage

typedef GPB_ENUM(ServerMessage_FieldNumber) {
  ServerMessage_FieldNumber_Version = 1,
  ServerMessage_FieldNumber_Type = 2,
  ServerMessage_FieldNumber_PayloadArray = 100,
};

@interface ServerMessage : GPBMessage

@property(nonatomic, readwrite) int32_t version;

@property(nonatomic, readwrite) int32_t type;

// |payloadArray| contains |GPBAny|
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray *payloadArray;
@property(nonatomic, readonly) NSUInteger payloadArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

// @@protoc_insertion_point(global_scope)
