// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: phone_information.proto

#import "GPBProtocolBuffers_RuntimeSupport.h"
#import "PhoneInformation.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma mark - PhoneInformationRoot

@implementation PhoneInformationRoot

@end

#pragma mark - PhoneInformationRoot_FileDescriptor

static GPBFileDescriptor *PhoneInformationRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPBDebugCheckRuntimeVersion();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@""
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - PhoneInformationRequest

@implementation PhoneInformationRequest

@dynamic phoneType;
@dynamic phoneVersion;
@dynamic longItude;
@dynamic latItude;
@dynamic requestTime;
@dynamic binaryPortInfor;

typedef struct PhoneInformationRequest__storage_ {
  uint32_t _has_storage_[1];
  int32_t phoneVersion;
  NSString *phoneType;
  NSString *longItude;
  NSString *latItude;
  NSString *requestTime;
  NSData *binaryPortInfor;
} PhoneInformationRequest__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "phoneType",
        .number = PhoneInformationRequest_FieldNumber_PhoneType,
        .hasIndex = 0,
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeString,
        .offset = offsetof(PhoneInformationRequest__storage_, phoneType),
        .defaultValue.valueString = nil,
        .dataTypeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "phoneVersion",
        .number = PhoneInformationRequest_FieldNumber_PhoneVersion,
        .hasIndex = 1,
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeInt32,
        .offset = offsetof(PhoneInformationRequest__storage_, phoneVersion),
        .defaultValue.valueInt32 = 0,
        .dataTypeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "longItude",
        .number = PhoneInformationRequest_FieldNumber_LongItude,
        .hasIndex = 2,
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeString,
        .offset = offsetof(PhoneInformationRequest__storage_, longItude),
        .defaultValue.valueString = nil,
        .dataTypeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "latItude",
        .number = PhoneInformationRequest_FieldNumber_LatItude,
        .hasIndex = 3,
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeString,
        .offset = offsetof(PhoneInformationRequest__storage_, latItude),
        .defaultValue.valueString = nil,
        .dataTypeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "requestTime",
        .number = PhoneInformationRequest_FieldNumber_RequestTime,
        .hasIndex = 4,
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeString,
        .offset = offsetof(PhoneInformationRequest__storage_, requestTime),
        .defaultValue.valueString = nil,
        .dataTypeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "binaryPortInfor",
        .number = PhoneInformationRequest_FieldNumber_BinaryPortInfor,
        .hasIndex = 5,
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeBytes,
        .offset = offsetof(PhoneInformationRequest__storage_, binaryPortInfor),
        .defaultValue.valueData = nil,
        .dataTypeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
    };
#if GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    const char *extraTextFormatInfo = NULL;
#else
    static const char *extraTextFormatInfo = "\006\001\t\000\002\014\000\003\t\000\004\010\000\005\013\000\006\017\000";
#endif  // GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[PhoneInformationRequest class]
                                     rootClass:[PhoneInformationRoot class]
                                          file:PhoneInformationRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:sizeof(fields) / sizeof(GPBMessageFieldDescription)
                                        oneofs:NULL
                                    oneofCount:0
                                         enums:NULL
                                     enumCount:0
                                        ranges:NULL
                                    rangeCount:0
                                   storageSize:sizeof(PhoneInformationRequest__storage_)
                                    wireFormat:NO
                           extraTextFormatInfo:extraTextFormatInfo];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


// @@protoc_insertion_point(global_scope)
