// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: phone_information.proto

#import "GPBProtocolBuffers.h"

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30000
#error This file was generated by a different version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - PhoneInformationRoot

@interface PhoneInformationRoot : GPBRootObject

// The base class provides:
//   + (GPBExtensionRegistry *)extensionRegistry;
// which is an GPBExtensionRegistry that includes all the extensions defined by
// this file and all files that it depends on.

@end

#pragma mark - PhoneInformationRequest

typedef GPB_ENUM(PhoneInformationRequest_FieldNumber) {
  PhoneInformationRequest_FieldNumber_PhoneType = 1,
  PhoneInformationRequest_FieldNumber_PhoneVersion = 2,
  PhoneInformationRequest_FieldNumber_LongItude = 3,
  PhoneInformationRequest_FieldNumber_LatItude = 4,
  PhoneInformationRequest_FieldNumber_RequestTime = 5,
  PhoneInformationRequest_FieldNumber_BinaryPortInfor = 6,
};

@interface PhoneInformationRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *phoneType;

@property(nonatomic, readwrite) int32_t phoneVersion;

@property(nonatomic, readwrite, copy, null_resettable) NSString *longItude;

@property(nonatomic, readwrite, copy, null_resettable) NSString *latItude;

@property(nonatomic, readwrite, copy, null_resettable) NSString *requestTime;

@property(nonatomic, readwrite, copy, null_resettable) NSData *binaryPortInfor;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

// @@protoc_insertion_point(global_scope)
