// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: topsec_corephoto.proto

#import "GPBProtocolBuffers.h"

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30000
#error This file was generated by a different version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - TopsecCorephotoRoot

@interface TopsecCorephotoRoot : GPBRootObject

// The base class provides:
//   + (GPBExtensionRegistry *)extensionRegistry;
// which is an GPBExtensionRegistry that includes all the extensions defined by
// this file and all files that it depends on.

@end

#pragma mark - TopsecMobileMessage

typedef GPB_ENUM(TopsecMobileMessage_FieldNumber) {
  TopsecMobileMessage_FieldNumber_Version = 1,
  TopsecMobileMessage_FieldNumber_Type = 2,
  TopsecMobileMessage_FieldNumber_MobileId = 3,
  TopsecMobileMessage_FieldNumber_MobileToken = 4,
  TopsecMobileMessage_FieldNumber_WhereServer = 5,
  TopsecMobileMessage_FieldNumber_Whereport = 6,
  TopsecMobileMessage_FieldNumber_BinaryContent = 7,
};

@interface TopsecMobileMessage : GPBMessage

@property(nonatomic, readwrite) int32_t version;

@property(nonatomic, readwrite) int32_t type;

//手机唯一标示 代表哪个手机发送的
@property(nonatomic, readwrite, copy, null_resettable) NSString *mobileId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *mobileToken;

//请求哪个平台
@property(nonatomic, readwrite, copy, null_resettable) NSString *whereServer;

//请求哪个接口
@property(nonatomic, readwrite, copy, null_resettable) NSString *whereport;

@property(nonatomic, readwrite, copy, null_resettable) NSData *binaryContent;

@end

#pragma mark - TopsecServerMessage

typedef GPB_ENUM(TopsecServerMessage_FieldNumber) {
  TopsecServerMessage_FieldNumber_Version = 101,
  TopsecServerMessage_FieldNumber_Type = 102,
  TopsecServerMessage_FieldNumber_MobileId = 103,
  TopsecServerMessage_FieldNumber_Whereport = 104,
  TopsecServerMessage_FieldNumber_BinaryContent = 105,
};

@interface TopsecServerMessage : GPBMessage

@property(nonatomic, readwrite) int32_t version;

@property(nonatomic, readwrite) int32_t type;

//手机唯一标示 代表哪个手机发送的
@property(nonatomic, readwrite, copy, null_resettable) NSString *mobileId;

//请求哪个接口
@property(nonatomic, readwrite, copy, null_resettable) NSString *whereport;

@property(nonatomic, readwrite, copy, null_resettable) NSData *binaryContent;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

// @@protoc_insertion_point(global_scope)
